### ISSUE TITLE
Accessing IMU on nano rp2040 connect stops timer

### ISSUE THREAD

**Issue by perry-pli** [khoih-prog/MBED_RPI_PICO_TimerInterrupt#2]
### Describe the bug

Repeating timer does not function properly when ISR accesses the I2C IMU sensor on the nano rp2040 connect.

### Steps to Reproduce: 
Copy and run the code above (after installing the Arduino_LSM6DSOX library) with and without the 2 lines in the timer_callback() ISR.

#include <Arduino_LSM6DSOX.h>
#include <stdio.h>
#include <mbed.h>
#define _TIMERINTERRUPT_LOGLEVEL_     4
#include "MBED_RPi_Pico_TimerInterrupt.h"

MBED_RPI_PICO_Timer ITimer0(0);

// IMU related
float Ax, Ay, Az;
float Gx, Gy, Gz;

void setup() 
  pinMode(LED_BUILTIN, OUTPUT);
  Serial.begin(115200);
  while(!Serial);
  if (!IMU.begin()) {
    Serial.println("Failed to initialize IMU!");
    while (1); // hangs
  }
  Serial.print("Accelerometer sample rate = ");
  Serial.print(IMU.accelerationSampleRate());
  Serial.println("Hz");
  Serial.println();

  Serial.print("Gyroscope sample rate = ");  
  Serial.print(IMU.gyroscopeSampleRate());
  Serial.println("Hz");
  
  ITimer0.attachInterruptInterval(1000000, timer_callback);
}

void loop() {
}

void timer_callback(uint alarm_num) {
  TIMER_ISR_START(alarm_num);
  digitalWrite(LED_BUILTIN, HIGH);
  sleep_ms(500);
  // *** Irregular LED flashing when the next 2 lines are uncommented ***
  //IMU.readAcceleration(Ax, Ay, Az);
  //IMU.readGyroscope(Gx, Gy, Gz);
  digitalWrite(LED_BUILTIN, LOW);
  TIMER_ISR_START(alarm_num);
}

### Expected behavior

LED should blink at 1Hz frequency (500ms on, approx 500ms off)

### Actual behavior

When accessing IMU (uncommenting the two lines in timer_callback()), the LED blinks irregularly. IMU takes 2ms but the irregular flashings are much more pronounced and definitely not at 1Hz.

### Information

* Arduino IDE version 1.8.19) on iMac
* Nano RP2040 connect
* The IMU sensor uses I2C, would there be conflict?

**Comment by khoih-prog** [comment]
Hi @perry-pli 

Thanks for **over-trusting** the library.

I suggest that you spend some more time to have better knowledge and experience with the **ISR**, before using it in over-killing way.

Try either to 

1. use ISR to set up a flag, then use software timer to periodically read the flag and read IMU
2. use only software timer to periodically read the IMU

More to read => [**Interrupts HOWTO**](http://gammon.com.au/interrupts) and [**attachinterrupt HOWTO**](https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt/)

**Comment by perry-pli** [comment]
Kindly please explain why your timer can't work with the sensor - even with very low frequency.

**Comment by khoih-prog** [comment]
> I suggest that you spend some more time to have better knowledge and experience with the ISR, before using it in over-killing way.

**Comment by perry-pli** [comment]
Having read through the links that you provide, I still don't have a sense of what is breaking your timer. In what way is the example code using your timer in an over-killing way?
